name: ETL F1 to GCS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  extract_transform_load:
    runs-on: ubuntu-latest
    env:
      DEV_MODE: "True"
    
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: 1. Extract (Capa Bronze)
        run: python scripts/extract.py
          
      - name: 2. Transform (Capa Silver - DuckDB)
        run: python scripts/transform_silver_laps.py

      - name: 3. Load (Simulacion Hive-style)
        run: python scripts/load.py